// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: proto/model/v1/user.proto

package usermodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User represents a user entity.
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Scram    *Scram `protobuf:"bytes,2,opt,name=scram,proto3" json:"scram,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_v1_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetScram() *Scram {
	if x != nil {
		return x.Scram
	}
	return nil
}

type Scram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sha1           string `protobuf:"bytes,1,opt,name=sha1,proto3" json:"sha1,omitempty"`
	Sha256         string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Sha512         string `protobuf:"bytes,3,opt,name=sha512,proto3" json:"sha512,omitempty"`
	Sha3512        string `protobuf:"bytes,4,opt,name=sha3512,proto3" json:"sha3512,omitempty"`
	IterationCount int64  `protobuf:"varint,5,opt,name=iteration_count,json=iterationCount,proto3" json:"iteration_count,omitempty"`
	Salt           string `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
	PepperId       string `protobuf:"bytes,7,opt,name=pepper_id,json=pepperId,proto3" json:"pepper_id,omitempty"`
}

func (x *Scram) Reset() {
	*x = Scram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_v1_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scram) ProtoMessage() {}

func (x *Scram) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scram.ProtoReflect.Descriptor instead.
func (*Scram) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *Scram) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *Scram) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Scram) GetSha512() string {
	if x != nil {
		return x.Sha512
	}
	return ""
}

func (x *Scram) GetSha3512() string {
	if x != nil {
		return x.Sha3512
	}
	return ""
}

func (x *Scram) GetIterationCount() int64 {
	if x != nil {
		return x.IterationCount
	}
	return 0
}

func (x *Scram) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *Scram) GetPepperId() string {
	if x != nil {
		return x.PepperId
	}
	return ""
}

var File_proto_model_v1_user_proto protoreflect.FileDescriptor

var file_proto_model_v1_user_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x4e, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a,
	0x0a, 0x05, 0x73, 0x63, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63,
	0x72, 0x61, 0x6d, 0x52, 0x05, 0x73, 0x63, 0x72, 0x61, 0x6d, 0x22, 0xbf, 0x01, 0x0a, 0x05, 0x53,
	0x63, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x61, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x68, 0x61, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32,
	0x35, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x35, 0x31, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x68, 0x61, 0x35, 0x31, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x61, 0x33,
	0x35, 0x31, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x68, 0x61, 0x33, 0x35,
	0x31, 0x32, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x74, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x65, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x70, 0x70, 0x65, 0x72, 0x49, 0x64, 0x42, 0x1b, 0x5a, 0x19,
	0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x3b,
	0x75, 0x73, 0x65, 0x72, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_model_v1_user_proto_rawDescOnce sync.Once
	file_proto_model_v1_user_proto_rawDescData = file_proto_model_v1_user_proto_rawDesc
)

func file_proto_model_v1_user_proto_rawDescGZIP() []byte {
	file_proto_model_v1_user_proto_rawDescOnce.Do(func() {
		file_proto_model_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_v1_user_proto_rawDescData)
	})
	return file_proto_model_v1_user_proto_rawDescData
}

var file_proto_model_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_model_v1_user_proto_goTypes = []interface{}{
	(*User)(nil),  // 0: model.user.v1.User
	(*Scram)(nil), // 1: model.user.v1.Scram
}
var file_proto_model_v1_user_proto_depIdxs = []int32{
	1, // 0: model.user.v1.User.scram:type_name -> model.user.v1.Scram
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_model_v1_user_proto_init() }
func file_proto_model_v1_user_proto_init() {
	if File_proto_model_v1_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_v1_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_v1_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_v1_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_v1_user_proto_goTypes,
		DependencyIndexes: file_proto_model_v1_user_proto_depIdxs,
		MessageInfos:      file_proto_model_v1_user_proto_msgTypes,
	}.Build()
	File_proto_model_v1_user_proto = out.File
	file_proto_model_v1_user_proto_rawDesc = nil
	file_proto_model_v1_user_proto_goTypes = nil
	file_proto_model_v1_user_proto_depIdxs = nil
}
