// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/model/roster.proto

package rostermodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item represents a roster item entity.
type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username     string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Jid          string   `protobuf:"bytes,2,opt,name=jid,proto3" json:"jid,omitempty"`
	Name         string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subscription string   `protobuf:"bytes,4,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Ask          bool     `protobuf:"varint,5,opt,name=ask,proto3" json:"ask,omitempty"`
	Groups       []string `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_roster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_roster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_model_roster_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Item) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *Item) GetAsk() bool {
	if x != nil {
		return x.Ask
	}
	return false
}

func (x *Item) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_proto_model_roster_proto protoreflect.FileDescriptor

var file_proto_model_roster_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x72, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x96, 0x01, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6a, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73,
	0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x42, 0x1e, 0x5a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x3b, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_roster_proto_rawDescOnce sync.Once
	file_proto_model_roster_proto_rawDescData = file_proto_model_roster_proto_rawDesc
)

func file_proto_model_roster_proto_rawDescGZIP() []byte {
	file_proto_model_roster_proto_rawDescOnce.Do(func() {
		file_proto_model_roster_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_roster_proto_rawDescData)
	})
	return file_proto_model_roster_proto_rawDescData
}

var file_proto_model_roster_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_model_roster_proto_goTypes = []interface{}{
	(*Item)(nil), // 0: model.roster.v1.Item
}
var file_proto_model_roster_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_roster_proto_init() }
func file_proto_model_roster_proto_init() {
	if File_proto_model_roster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_roster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_roster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_roster_proto_goTypes,
		DependencyIndexes: file_proto_model_roster_proto_depIdxs,
		MessageInfos:      file_proto_model_roster_proto_msgTypes,
	}.Build()
	File_proto_model_roster_proto = out.File
	file_proto_model_roster_proto_rawDesc = nil
	file_proto_model_roster_proto_goTypes = nil
	file_proto_model_roster_proto_depIdxs = nil
}
