version: '3'
volumes:
  etcd:
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.16
    ports:
      - 2379
    volumes:
      - etcd:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380

  pgsql:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=jackal
      - POSTGRES_PASSWORD=asecretpassword
    volumes:
      - ../sql/postgres.up.psql:/docker-entrypoint-initdb.d/01-schema.sql

  jackal:
    image: ortuman/jackal:latest
    ports:
      - 5222:5222
    depends_on:
      - etcd
      - pgsql
    working_dir: /jackal
    volumes:
      - ../scripts/wait-for-it.sh:/jackal/wait-for-it.sh
      - ../config/docker-compose.config.yaml:/jackal/config.yaml
    command:
      - ./wait-for-it.sh
      - pgsql:5432
      - --
      - ./wait-for-it.sh
      - etcd:2379
      - --
      - ./jackal
