{
 "title": "Jackal - XMPP Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": "jackal" }
  ]
 },
 "panels": [
  { "title": "🙎‍♂️🔌 C2S", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "C2S Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jackal_c2s_incoming_total_connections)"
    }
   ]
  },
  {
   "title": "C2S Incoming (op/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (rate(jackal_c2s_incoming_requests_total[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "C2S Outgoing (op/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (rate(jackal_c2s_outgoing_requests_total[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "C2S Request Latency (seg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jackal_c2s_incoming_requests_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(jackal_c2s_incoming_requests_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(jackal_c2s_incoming_requests_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "🖥️ 🔌  S2S", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "S2S In Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jackal_s2s_incoming_total_connections)"
    }
   ]
  },
  {
   "title": "S2S Out Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jackal_s2s_outgoing_total_connections)"
    }
   ]
  },
  {
   "title": "S2S Incoming (op/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (rate(jackal_s2s_incoming_requests_total[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "S2S Outgoing (op/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (rate(jackal_s2s_outgoing_requests_total[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "S2S Request Latency (seg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jackal_s2s_incoming_requests_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(jackal_c2s_incoming_requests_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(jackal_c2s_incoming_requests_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "💽 Repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Repository Operations (op/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (rate(jackal_repository_operations_duration_bucket_count{success=\"true\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Repository Latency (seg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jackal_repository_operations_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(jackal_repository_operations_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(jackal_repository_operations_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "🕹️ KV Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "KV Operations (op/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (rate(jackal_kv_operations_duration_bucket_count{success=\"true\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "KV Latency (seg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jackal_kv_operations_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(jackal_kv_operations_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(jackal_kv_operations_duration_bucket_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "⚡ System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total{job=\"$job\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\"}"
    }
   ]
  },
  { "title": "🔆 Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}"
    }
   ]
  }
 ]
}