name: "Tests"

on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.1'

      - name: Setup moq
        run: go get github.com/matryer/moq

      - name: Run tests
        run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.7
        with:
          file: coverage.txt
